# https://hub.docker.com/r/pydio/cells/tags
# https://hub.docker.com/_/mysql/tags

version: '3.8'

services:
  pydio:
    image: 'docker.io/pydio/cells:4.3.5'
    ports:
      - '8080:8080/tcp'
    volumes:
      - 'pydio:/var/cells'
      - 'datasources:/var/cells/data'
    environment:
      DATABASE_NAME: 'cells'
      DATABASE_HOST: 'db'
      DATABASE_PASSWORD: 'pydio'
    stop_grace_period: '60s'
    restart: 'always'

  db:
    image: 'docker.io/library/mysql:8'
    environment:
      MYSQL_ROOT_PASSWORD: 'correct horse battery staple'
      MYSQL_DATABASE: 'cells'
      MYSQL_USER: 'pydio'
      MYSQL_PASSWORD: 'pydio'
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    volumes:
      - 'db:/var/lib/mysql'
    stop_grace_period: '90s'
    restart: 'always'

volumes:
  datasources:
    external: true
  pydio:
    external: true
  db:
    external: true
