# https://hub.docker.com/r/sonatype/nexus3/tags
# https://github.com/sonatype/docker-nexus3

version: '3.8'

services:
  nexus:
    image: 'docker.io/sonatype/nexus3:3.65.0'
    ports:
      - '8081:8081/tcp'
    volumes:
      - 'data:/nexus-data'
      - 'blobs:/nexus-data/blobs/'
    stop_grace_period: '180s'
    restart: 'always'

volumes:
  data:
  blobs:
