# Links:
#   https://hub.docker.com/r/sonatype/nexus3/tags
#   https://github.com/sonatype/docker-nexus3

# Create volumes before first run:
#   docker volume create nexus
#   docker volume create nexus-blobs

# Get admin password:
#   docker exec nexus /bin/cat /nexus-data/admin.password

version: '3.8'

services:
  nexus:
    container_name: 'nexus'
    image: 'docker.io/sonatype/nexus3:3.65.0'
    ports:
      - '8081:8081/tcp'
    volumes:
      - 'nexus:/nexus-data'
      - 'nexus-blobs:/nexus-data/blobs/'
    stop_grace_period: '180s'
    restart: 'always'

volumes:
  nexus:
    external: true
  nexus-blobs:
    external: true
